### ISSUE TITLE
[FeedBack][New Feature Request]

### ISSUE THREAD

**Issue by Claire** [GarinZ/link-map#27]
## Description
When I use the search input box at the top it doesn't include the raw url in the search only the titles

## Steps to reproduce (if applicable)

- search for a string that you know is part of a url of a window/tab in the list 
- its not listed in the search results

## Expected behavior
It would be nice even if its an preference switch to have the search include the tabs *urls in its matching code

## Actual behavior
- its not listed in the search results

Otherwise the extension is fantastic! Thanks so much for creating it. If you need help with the closing/fixing bugs let me know

**Comment by GarinZ** [comment]
@Claire Good suggestion, It will be added, and Link Map will include more options for search box. I think other users (including me) need it too.

**Comment by GarinZ** [comment]
Hi @Claire,
Search include URL has been released in v1.1.0. Hope this will be helpful.
![](https://user-images.githubusercontent.com/7566103/236665277-c599f182-7a1f-4b98-b66a-2efe64ca2897.gif)
