### ISSUE TITLE
[FeedBack] Please make the extension retain the last size and position 

### ISSUE THREAD

**Issue by Claire** [GarinZ/link-map#31]
## Description
When launching the Link Map window it opens on the right but I prefer it on the left and always have to move it
it would be awesome delighter if it retained the size and position it was set to last time it was used so that it can open to that same size and location the next time it it launched and the next time the browser restarts.

Thanks for a great tool!

**Comment by GarinZ** [comment]
Sure, I forgot this feature. You will see it in the next version.

**Comment by staalman** [comment]
Good point. Also my experience. configurable presets and a 'memory'  setting would be great!

**Comment by GarinZ** [comment]
Configurable presets is in schedule, I will add it in the future version

**Comment by GarinZ** [comment]
> Good point. Also my experience. configurable presets and a 'memory' setting would be great!

Configurable presets is in schedule, I will add it in the future version

**Comment by GarinZ** [comment]
This feature called 'Open with Last Closed Position/Size' has been released in v1.1.0. Now you could check it in setting.
