### ISSUE TITLE
[Feature] 希望添加快捷关闭 LinkMap 方式，比如再次激活关闭 LinkMap 侧边栏

### ISSUE THREAD

**Issue by yxmg** [GarinZ/link-map#32]
在 Chrome 中我可以快速通过激活拓展快捷键来唤起 LinkMap，但却无法通过再次激活收起 LinkMap 需要手动点击 LinkMap 顶部栏 ❎ 来关闭

**Comment by GarinZ** [comment]
@yxmg 
感谢反馈，我也收到了来自其他用户的类似需求，我会在之后版本中增加配置，让您和其他用户可以选择“点击扩展按钮“和”打开LinkMap快捷键“的行为是“开启/激活”还是"开启/关闭"

---
Thanks for the feedback, I also received a similar demand from other users, I will add the configuration in a later version, allows you and other users to choose the behavior of "Click the extension button" and "Open LinkMap shortcut" as "open/activate" or"open/close" actions

**Comment by GarinZ** [comment]
Hi @yxmg,
This feature has been added after v1.1.0. Now you could config it in settings.
