### ISSUE TITLE
[New Feature Asking] Make Ctrl+K and user definable shortcut

### ISSUE THREAD

**Issue by andycjw** [GarinZ/link-map#35]
it would be very useful if the search bar in link map can be activated by extension shortcut, and make it user defined

e.g. I can quickly find and search the tab in link map, by using alt+K

it would be great if we can scroll the result with keyboard, e.g. pressing j,k to go up and down to the result to jump to the tab we want directly

**Comment by GarinZ** [comment]
@andycjw Nice suggeestion. I will add these to next version.

**Comment by GarinZ** [comment]
Hi @andycjw,
After v1.1.0, Global Search Shortcut has been added to Link Map. With this shortcut, you could trigger Link Map search globally.
