### ISSUE TITLE
New Tabs and Duplicated Tabs end up in the wrong spot in the LinkMap list

### ISSUE THREAD

**Issue by staalman** [GarinZ/link-map#40]
## Description
When duplicating an existing Tab in Chrome, or when Creating a New Tab right next to the currently selected Tab, the [new or duplicated) tab opens right next to the source tab that was being duplicated or the tab that was active. This is the case with or without other open tabs to the right of the selected tab.
In the LinkMap list however, this new tab always shows up last in the list, regardless of the place in the list of open Tabs in the Chrome browser.

## Steps to reproduce (if applicable)
1. open 3 Tabs
2. Select Tab 1.
3. Duplicate Tab 1 to the right of it.
4. there is now Tab 1 - 4 - 2 -3 in chrome, but 1 - 2 - 3 - 4 in Link Map

## Expected behaviour
Expected is to respect the sequence as shown in the browser in the Link Map list.

## Actual behaviour
Always puts new and duplicated tabs at the end of the LinkMap list.

**Comment by GarinZ** [comment]
Hi @staalman,
Thanks for your report. I have found this issue, and fix it in the v1.1.0(under reviewing in Web Store). After this update released, this issue will be fixed.

**Comment by GarinZ** [comment]
This bug has been fixed in v1.1.0.
