### ISSUE TITLE
[Bug Report] After exiting chrome w/o closing Link Map first, it can't be opened after relaunching chrome.

### ISSUE THREAD

**Issue by Max33Verstappen** [GarinZ/link-map#45]
## Description
Using Chrome menu -> Exit while the window of Link Map is still open, next time, after starting chrome, Link Map can't be opened, unless manually delete `%LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\jappgmhllahigjolfpgbjdfhciabdnde\000003.log`.

## Steps to reproduce (if applicable)
Leave the window of Link Map open and use Chrome menu -> Exit.
## Expected behavior
[Describe what you expected to happen.]
## Actual behavior
After chrome restart, Link Map won't open.

**Comment by GarinZ** [comment]
@Max33Verstappen Thanks for your report, I will check this issue.

**Comment by GarinZ** [comment]
@Max33Verstappen 
I'm sorry that it is indeed a bug. I have fixed it in v1.1.1, which has been released in Chrome Web Store.
After updating, this bug will be fixed.
