### ISSUE TITLE
[New Feature Asking] More way to move the cursor using a keyboard.

### ISSUE THREAD

**Issue by Max33Verstappen** [GarinZ/link-map#46]
## Description
I find the only way to move the cursor using a keyboard is the `Up` and `Down` arrows.
When one has a really long tree, this can be a problem.
And the keys `PageDown` and `PageUp` only do the scrolling but don't move the cursor.
The key `End` move the cursor to the end of the tree list.

## Expected behavior
In Tabs Outliner,  `PageDown` and `PageUp` move the cursor down/up by 10 rows. 
The `End` key moves the cursor to the end of the **SAME level** the cursor is currently at.
I find these behaviors quite convenient when the list is long. (Though all the keyboard maneuvers in Tabs Outliner are paid features).
You may consider these features or they can be put in the PRO.

## Actual behavior
`PgDn` and `PgUp` don't move the cursor.
`End` put the cursor at the end of the entire tree.

**Comment by GarinZ** [comment]
Hi @Max33Verstappen,
Nice suggestion. I miss these. I usally work with MacOS.
Thanks for considering Pro. And this is feature is quite simple and I'd love to give all user full access to the shortcut for free. 
I will add these in the next version after fixing your reported bug.

**Comment by GarinZ** [comment]
Hi @Max33Verstappen,
In v1.1.3, which has been released in Chrome just now, I have introduced `PageDown/PageUp` as the shortcut of Skip Down/Up 10 nodes, and `Shift + Home/End` as the shortcut of Go to the first/last sibling.
