### ISSUE TITLE
[FeedBack] Subscription is gone after switch to side-panel mode and cannot re-enter license code.

### ISSUE THREAD

**Issue by molamooo** [GarinZ/link-map#62]
## Description
Subscription is gone after switch to sidebar mode and cannot re-enter license code.
## Steps to reproduce (if applicable)
- Install link map and activate with license code normally
- Set link map open mode into side panel
## Expected behavior
- Link map works normally with payed features
## Actual behavior
- Subsription is gone
- Link map hangs when activating with previous license code
## Screenshots (if applicable)
<img width="430" alt="image" src="https://github.com/GarinZ/link-map/assets/28782336/0dd77f79-4dac-44db-9923-f0ca0d81be69">
<img width="462" alt="image" src="https://github.com/GarinZ/link-map/assets/28782336/524fc481-10ca-417c-86b4-76360dd7597e">

## Additional information
I've tried to uninstall and re-install link map. The activation autmatically recovers when I login with google account. But after switching to side panel, the subscription still vanishes. Re-enterring license code still hangs.

**Comment by GarinZ** [comment]
Hi @Jeffery-Song,
Thanks for reporting this! I will try to fix this as soon as possible.
After this bug has been fixed, I will inform you in this issue.

**Comment by GarinZ** [comment]
I have submit a patch(v1.1.5) in Chrome Web Store. After v1.1.5 released (about 2 days for review), this issue will be fixed.
